[project]
name = "investment-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rui Xue", email = "ruixue.fi@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.34.2",
    "yfinance>=1.6.0",
]

[project.scripts]
investment = "investment.cli.main:main"

[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "investment"
